#!/usr/bin/env python

# Copyright 2016 Jim Pivarski
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import math
import pickle
import unittest

from histogrammar import *
from histogrammar.histogram import Histogram

class Struct(object):
    def __init__(self, x, y, z, w):
        self.bool = x
        self.int = y
        self.double = z
        self.string = w
    def __repr__(self):
        return "Struct({}, {}, {}, {})".format(self.bool, self.int, self.double, repr(self.string))

def ed(x):
    return Factory.fromJson(x.toJson())

class TestEverything(unittest.TestCase):
    def assertAlmostEqualJSON(self, x, y):
        if isinstance(x, dict) and isinstance(y, dict):
            if set(x.keys()) == set(y.keys()):
                for k in x.keys():
                    self.assertAlmostEqualJSON(x[k], y[k])
            else:
                raise AssertionError("keys {} are not equal to keys {}".format(sorted(x.keys()), sorted(y.keys())))

        elif isinstance(x, list) and isinstance(y, list):
            if len(x) == len(y):
                for xi, yi in zip(x, y):
                    self.assertAlmostEqualJSON(xi, yi)
            else:
                raise AssertionError("length of {} is not equal to length of {}".format(x, y))

        elif isinstance(x, basestring) and isinstance(y, basestring):
            self.assertEqual(x, y)

        elif isinstance(x, (int, long, float)) and isinstance(y, (int, long, float)):
            self.assertAlmostEqual(x, y)

        else:
            self.assertEqual(x, y)

    def test_count(self):
        x = Count()
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(3.4)
        self.assertAlmostEqualJSON(x.toJson(), {'data': 1.0, 'type': 'Count'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(2.2)
        self.assertAlmostEqualJSON(x.toJson(), {'data': 2.0, 'type': 'Count'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(-1.8)
        self.assertAlmostEqualJSON(x.toJson(), {'data': 3.0, 'type': 'Count'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(0.0)
        self.assertAlmostEqualJSON(x.toJson(), {'data': 4.0, 'type': 'Count'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(7.3)
        self.assertAlmostEqualJSON(x.toJson(), {'data': 5.0, 'type': 'Count'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(-4.7)
        self.assertAlmostEqualJSON(x.toJson(), {'data': 6.0, 'type': 'Count'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(1.6)
        self.assertAlmostEqualJSON(x.toJson(), {'data': 7.0, 'type': 'Count'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(0.0)
        self.assertAlmostEqualJSON(x.toJson(), {'data': 8.0, 'type': 'Count'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(-3.0)
        self.assertAlmostEqualJSON(x.toJson(), {'data': 9.0, 'type': 'Count'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(-1.7)
        self.assertAlmostEqualJSON(x.toJson(), {'data': 10.0, 'type': 'Count'})

    def test_weightedCount(self):
        x = Count()
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(3.14, 3.4)
        self.assertAlmostEqualJSON(x.toJson(), {'data': 3.4, 'type': 'Count'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(3.14, 2.2)
        self.assertAlmostEqualJSON(x.toJson(), {'data': 5.6, 'type': 'Count'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(3.14, -1.8)
        self.assertAlmostEqualJSON(x.toJson(), {'data': 5.6, 'type': 'Count'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(3.14, 0.0)
        self.assertAlmostEqualJSON(x.toJson(), {'data': 5.6, 'type': 'Count'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(3.14, 7.3)
        self.assertAlmostEqualJSON(x.toJson(), {'data': 12.899999999999999, 'type': 'Count'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(3.14, -4.7)
        self.assertAlmostEqualJSON(x.toJson(), {'data': 12.899999999999999, 'type': 'Count'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(3.14, 1.6)
        self.assertAlmostEqualJSON(x.toJson(), {'data': 14.499999999999998, 'type': 'Count'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(3.14, 0.0)
        self.assertAlmostEqualJSON(x.toJson(), {'data': 14.499999999999998, 'type': 'Count'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(3.14, -3.0)
        self.assertAlmostEqualJSON(x.toJson(), {'data': 14.499999999999998, 'type': 'Count'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(3.14, -1.7)
        self.assertAlmostEqualJSON(x.toJson(), {'data': 14.499999999999998, 'type': 'Count'})

    def test_summ(self):
        x = Sum(lambda x: x + 1)
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(3.4)
        self.assertAlmostEqualJSON(x.toJson(), {'data': {'sum': 4.4, 'entries': 1.0}, 'type': 'Sum'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(2.2)
        self.assertAlmostEqualJSON(x.toJson(), {'data': {'sum': 7.6, 'entries': 2.0}, 'type': 'Sum'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(-1.8)
        self.assertAlmostEqualJSON(x.toJson(), {'data': {'sum': 6.8, 'entries': 3.0}, 'type': 'Sum'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(0.0)
        self.assertAlmostEqualJSON(x.toJson(), {'data': {'sum': 7.8, 'entries': 4.0}, 'type': 'Sum'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(7.3)
        self.assertAlmostEqualJSON(x.toJson(), {'data': {'sum': 16.1, 'entries': 5.0}, 'type': 'Sum'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(-4.7)
        self.assertAlmostEqualJSON(x.toJson(), {'data': {'sum': 12.399999999999999, 'entries': 6.0}, 'type': 'Sum'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(1.6)
        self.assertAlmostEqualJSON(x.toJson(), {'data': {'sum': 15.0, 'entries': 7.0}, 'type': 'Sum'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(0.0)
        self.assertAlmostEqualJSON(x.toJson(), {'data': {'sum': 16.0, 'entries': 8.0}, 'type': 'Sum'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(-3.0)
        self.assertAlmostEqualJSON(x.toJson(), {'data': {'sum': 14.0, 'entries': 9.0}, 'type': 'Sum'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(-1.7)
        self.assertAlmostEqualJSON(x.toJson(), {'data': {'sum': 13.3, 'entries': 10.0}, 'type': 'Sum'})

    def test_sumWithName(self):
        x = Sum(named('something', lambda x: x + 1))
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(3.4)
        self.assertAlmostEqualJSON(x.toJson(), {'data': {'sum': 4.4, 'name': 'something', 'entries': 1.0}, 'type': 'Sum'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(2.2)
        self.assertAlmostEqualJSON(x.toJson(), {'data': {'sum': 7.6, 'name': 'something', 'entries': 2.0}, 'type': 'Sum'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(-1.8)
        self.assertAlmostEqualJSON(x.toJson(), {'data': {'sum': 6.8, 'name': 'something', 'entries': 3.0}, 'type': 'Sum'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(0.0)
        self.assertAlmostEqualJSON(x.toJson(), {'data': {'sum': 7.8, 'name': 'something', 'entries': 4.0}, 'type': 'Sum'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(7.3)
        self.assertAlmostEqualJSON(x.toJson(), {'data': {'sum': 16.1, 'name': 'something', 'entries': 5.0}, 'type': 'Sum'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(-4.7)
        self.assertAlmostEqualJSON(x.toJson(), {'data': {'sum': 12.399999999999999, 'name': 'something', 'entries': 6.0}, 'type': 'Sum'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(1.6)
        self.assertAlmostEqualJSON(x.toJson(), {'data': {'sum': 15.0, 'name': 'something', 'entries': 7.0}, 'type': 'Sum'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(0.0)
        self.assertAlmostEqualJSON(x.toJson(), {'data': {'sum': 16.0, 'name': 'something', 'entries': 8.0}, 'type': 'Sum'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(-3.0)
        self.assertAlmostEqualJSON(x.toJson(), {'data': {'sum': 14.0, 'name': 'something', 'entries': 9.0}, 'type': 'Sum'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(-1.7)
        self.assertAlmostEqualJSON(x.toJson(), {'data': {'sum': 13.3, 'name': 'something', 'entries': 10.0}, 'type': 'Sum'})

    def test_sumByString(self):
        x = Sum('x + 1')
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(3.4)
        self.assertAlmostEqualJSON(x.toJson(), {'data': {'sum': 4.4, 'name': 'x + 1', 'entries': 1.0}, 'type': 'Sum'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(2.2)
        self.assertAlmostEqualJSON(x.toJson(), {'data': {'sum': 7.6, 'name': 'x + 1', 'entries': 2.0}, 'type': 'Sum'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(-1.8)
        self.assertAlmostEqualJSON(x.toJson(), {'data': {'sum': 6.8, 'name': 'x + 1', 'entries': 3.0}, 'type': 'Sum'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(0.0)
        self.assertAlmostEqualJSON(x.toJson(), {'data': {'sum': 7.8, 'name': 'x + 1', 'entries': 4.0}, 'type': 'Sum'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(7.3)
        self.assertAlmostEqualJSON(x.toJson(), {'data': {'sum': 16.1, 'name': 'x + 1', 'entries': 5.0}, 'type': 'Sum'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(-4.7)
        self.assertAlmostEqualJSON(x.toJson(), {'data': {'sum': 12.399999999999999, 'name': 'x + 1', 'entries': 6.0}, 'type': 'Sum'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(1.6)
        self.assertAlmostEqualJSON(x.toJson(), {'data': {'sum': 15.0, 'name': 'x + 1', 'entries': 7.0}, 'type': 'Sum'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(0.0)
        self.assertAlmostEqualJSON(x.toJson(), {'data': {'sum': 16.0, 'name': 'x + 1', 'entries': 8.0}, 'type': 'Sum'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(-3.0)
        self.assertAlmostEqualJSON(x.toJson(), {'data': {'sum': 14.0, 'name': 'x + 1', 'entries': 9.0}, 'type': 'Sum'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(-1.7)
        self.assertAlmostEqualJSON(x.toJson(), {'data': {'sum': 13.3, 'name': 'x + 1', 'entries': 10.0}, 'type': 'Sum'})

    def test_sumStruct(self):
        x = Sum(lambda x: x.double + 1)
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(Struct(True, -2, 3.4, 'one'))
        self.assertAlmostEqualJSON(x.toJson(), {'data': {'sum': 4.4, 'entries': 1.0}, 'type': 'Sum'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(Struct(False, -1, 2.2, 'two'))
        self.assertAlmostEqualJSON(x.toJson(), {'data': {'sum': 7.6, 'entries': 2.0}, 'type': 'Sum'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(Struct(True, 0, -1.8, 'three'))
        self.assertAlmostEqualJSON(x.toJson(), {'data': {'sum': 6.8, 'entries': 3.0}, 'type': 'Sum'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(Struct(False, 1, 0.0, 'four'))
        self.assertAlmostEqualJSON(x.toJson(), {'data': {'sum': 7.8, 'entries': 4.0}, 'type': 'Sum'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(Struct(False, 2, 7.3, 'five'))
        self.assertAlmostEqualJSON(x.toJson(), {'data': {'sum': 16.1, 'entries': 5.0}, 'type': 'Sum'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(Struct(False, 3, -4.7, 'six'))
        self.assertAlmostEqualJSON(x.toJson(), {'data': {'sum': 12.399999999999999, 'entries': 6.0}, 'type': 'Sum'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(Struct(True, 4, 1.6, 'seven'))
        self.assertAlmostEqualJSON(x.toJson(), {'data': {'sum': 15.0, 'entries': 7.0}, 'type': 'Sum'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(Struct(True, 5, 0.0, 'eight'))
        self.assertAlmostEqualJSON(x.toJson(), {'data': {'sum': 16.0, 'entries': 8.0}, 'type': 'Sum'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(Struct(False, 6, -3.0, 'nine'))
        self.assertAlmostEqualJSON(x.toJson(), {'data': {'sum': 14.0, 'entries': 9.0}, 'type': 'Sum'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(Struct(True, 7, -1.7, 'ten'))
        self.assertAlmostEqualJSON(x.toJson(), {'data': {'sum': 13.3, 'entries': 10.0}, 'type': 'Sum'})

    def test_sumStructString(self):
        x = Sum('double + 1')
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(Struct(True, -2, 3.4, 'one'))
        self.assertAlmostEqualJSON(x.toJson(), {'data': {'sum': 4.4, 'name': 'double + 1', 'entries': 1.0}, 'type': 'Sum'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(Struct(False, -1, 2.2, 'two'))
        self.assertAlmostEqualJSON(x.toJson(), {'data': {'sum': 7.6, 'name': 'double + 1', 'entries': 2.0}, 'type': 'Sum'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(Struct(True, 0, -1.8, 'three'))
        self.assertAlmostEqualJSON(x.toJson(), {'data': {'sum': 6.8, 'name': 'double + 1', 'entries': 3.0}, 'type': 'Sum'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(Struct(False, 1, 0.0, 'four'))
        self.assertAlmostEqualJSON(x.toJson(), {'data': {'sum': 7.8, 'name': 'double + 1', 'entries': 4.0}, 'type': 'Sum'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(Struct(False, 2, 7.3, 'five'))
        self.assertAlmostEqualJSON(x.toJson(), {'data': {'sum': 16.1, 'name': 'double + 1', 'entries': 5.0}, 'type': 'Sum'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(Struct(False, 3, -4.7, 'six'))
        self.assertAlmostEqualJSON(x.toJson(), {'data': {'sum': 12.399999999999999, 'name': 'double + 1', 'entries': 6.0}, 'type': 'Sum'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(Struct(True, 4, 1.6, 'seven'))
        self.assertAlmostEqualJSON(x.toJson(), {'data': {'sum': 15.0, 'name': 'double + 1', 'entries': 7.0}, 'type': 'Sum'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(Struct(True, 5, 0.0, 'eight'))
        self.assertAlmostEqualJSON(x.toJson(), {'data': {'sum': 16.0, 'name': 'double + 1', 'entries': 8.0}, 'type': 'Sum'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(Struct(False, 6, -3.0, 'nine'))
        self.assertAlmostEqualJSON(x.toJson(), {'data': {'sum': 14.0, 'name': 'double + 1', 'entries': 9.0}, 'type': 'Sum'})
        self.assertEqual(x, x)
        self.assertEqual(ed(x), ed(x))
        self.assertEqual(hash(x), hash(x))
        self.assertEqual(hash(ed(x)), hash(ed(x)))
        self.assertEqual(x, x + x.zero())
        self.assertEqual(ed(x), ed(x) + ed(x).zero())
        self.assertEqual(ed(x + x), ed(x) + ed(x))
        self.assertEqual(x, pickle.loads(pickle.dumps(x)))
        self.assertEqual(ed(x), pickle.loads(pickle.dumps(ed(x))))
        self.assertEqual(ed(x), ed(pickle.loads(pickle.dumps(x))))
        x.fill(Struct(True, 7, -1.7, 'ten'))
        self.assertAlmostEqualJSON(x.toJson(), {'data': {'sum': 13.3, 'name': 'double + 1', 'entries': 10.0}, 'type': 'Sum'})
