"""THIS FILE IS AUTO-GENERATED BY SETUP.PY."""

import re

version = "1.1.2"


def split_version_string(version_string: str) -> tuple[int, int]:
    version_numbers = list(map(int, re.split(r"[-.]", version_string)))
    return version_numbers[0], version_numbers[1]


specification = ".".join([str(i) for i in split_version_string(version)[:2]])


def compatible(serialized_version: str) -> bool:
    self_major, self_minor = split_version_string(version)
    other_major, other_minor = split_version_string(serialized_version)

    return bool(self_major >= other_major or self_minor >= other_minor)
