"""THIS FILE IS AUTO-GENERATED BY SETUP.PY."""

import re

name = "histogrammar"
__version__ = "1.0.24"
version = "1.0.24"
full_version = "1.0.24"
release = True

version_info = tuple(re.split(r"[-\.]", __version__))
specification = ".".join(version_info[:2])


def compatible(serializedVersion):
    selfMajor, selfMinor = map(int, version_info[:2])
    otherMajor, otherMinor = map(int, re.split(r"[-\.]", serializedVersion)[:2])
    if selfMajor >= otherMajor:
        return True
    elif selfMinor >= otherMinor:
        return True
    else:
        return False
